### ISSUE TITLE
trp-delete-phylotree hangs (or is very slow)

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/tripal_phylogeny#3]
just tried testing this drush command on lis-adf as:
drush trp-delete-phylotree --name=phytozome_11.59026785 --user=adf
messages received:
Getting nodes
Getting chado_phylotree
Verifying all chado_phylotree Entries
	1 chado_phylotree entries missing either a node or chado entry.
but it seems to be stuck there. haven't investigated any deeper into what it's doing yet

**Comment by adf-ncgr** [comment]
it does seem to be deleting the tree, though (even after a ctrl-c interrupt at the above point)

**Comment by guidorice** [comment]
Went to repro this, and found that our production branch of lis_master (formerly phylotree_count) does not even have the  tripal_phylotree.drush.inc file where these commands are defined. So really this issue dependent on getting all the code branches merged https://legume.atlassian.net/browse/LEGUME-272

**Comment by guidorice** [comment]
Latest comments are in JIRA.
